### ISSUE TITLE
The FOOTER to only display at the LAST PAGE

### ISSUE THREAD

**Issue by codestitch** [gregnb/react-to-print#685]
I have this page, in which it has a header (not using <header> or <thead> tag), table contents and a footer (not using <footer> or <tfoot> tag).

Currently, it has two pages, as seen in the screenshot. And the footer is displaying in each page. Currently, I'm using display: fixed, for the footer part. 

What I wanted to achieve is that, the footer would only shot at the last page.

Is there a way to do it?

![image](https://github.com/gregnb/react-to-print/assets/5573444/664a8880-3553-4d02-9041-2bfdf5ffb80b)

**Comment by ratnabh-classic** [comment]
Did you find any solution to it ?

**Comment by codestitch** [comment]
nope.

**Comment by MatthewHerbst** [comment]
Hi, apologies for the delayed response here. I feel like I've seen someone ask this before but I don't recall have they solved it. One option you might have is to change it so that it's not a `display: fixed` during the printing. Honestly, asking this in StackOverflow where there are many CSS experts might get you a better answer, as this question is fairly generic and not strictly related to react-to-print
